version: "3.7"
services:
    web: 
        build: .
        volumes:
            - ./site:/var/www/html
        ports:
            - 80:80
        depends_on:
            - db
    db:
        image: mysql
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_USER: user_root 
            MYSQL_PASSWORD: 123
            # MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: db_docker_newUser
        ports:
            - 3306:3306
        restart: 'always'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 12345
